### ISSUE TITLE
"Using Cabal on Its Own" is outdated

### ISSUE THREAD

**Issue by 23Skidoo** [kowainik/awesome-cabal#1]
Thanks for creating this list.

Just wanted to point out that information in the "Using Cabal on Its Own" post is no longer up-to-date as of `cabal-install` 3.0+, since `v2-build` is now the default and recommended mode of operation instead of sandboxes. `v1-build` is still there for backwards compatibility purposes.

**Comment by vrom911** [comment]
Thanks for pointing that out! This post indeed covers outdated information even though it has been published recently. As we would want to keep this list relevant to the current state of Cabal, I am going to remove this post from the list.
