### ISSUE TITLE
Add `cargo-cabal` to the list?

### ISSUE THREAD

**Issue by yvan-sraka** [kowainik/awesome-cabal#18]
Hi, I'm not sure what would be the best section for referencing https://github.com/yvan-sraka/cargo-cabal (that generate a `Cabal` project from a `cargo` one).

**Comment by vrom911** [comment]
Hi! Nice tool, thanks for sharing!
I thin either __Scaffolding__ or __Integration__ section would be great fit.
Feel free to open the PR for adding that :)
